fix uninitialized value and bad free
fvwmorg/fvwm3 pull request #447
Opened 2021-02-23 22:13 UTC by mikeandmore

fixed some heap corruption. 

Some of them can be triggered by start/restart fvwm.

2021-02-23 22:21 UTC, ThomasAdam requested changes
Hey @mikeandmore 

Thanks.  One style-nit I'd like you to fix, and a query regarding a `memset()`...

Can you amend the commit message, add:

```
Fixes #446 
```

2021-02-23 22:21 UTC, ThomasAdam commented on fvwm/add_window.c
> +			if (fw->visible_icon_name != NoName) free(fw->visible_icon_name);
Style-nit:

```
if (fw->visible_icon_name != NoName)
    free(fw->visible_icon_name);
```

2021-02-23 22:21 UTC, ThomasAdam commented on libs/FEvent.c
> +	memset(hints_return, 0, sizeof(XSizeHints));
I doubt this is strictly necessary?

2021-02-23 22:35 UTC, mikeandmore commented on libs/FEvent.c
> +	memset(hints_return, 0, sizeof(XSizeHints));
it is. we kinda ignore the hint masks.

2021-02-23 22:37 UTC, mikeandmore commented on fvwm/add_window.c
> +			if (fw->visible_icon_name != NoName) free(fw->visible_icon_name);
fixed.

2021-02-23 22:40 UTC, mikeandmore commented
> ```
> Fixes #446 
> ```

Does it actually fix that? I couldn't reproduce #446. Does this patch work for you?

2021-02-24 22:11 UTC, mikeandmore commented
This commit fixes #446

2021-02-24 22:14 UTC, merged