add a CursorSet command
fvwmorg/fvwm3 pull request #448
Opened 2021-02-24 05:14 UTC by mikeandmore

`CursorSet` can set an absolute mouse cursor position. This is helpful for save and restoring mouse cursor positions.

On IRC, we talked about support some auto mouse move features from CWM. With `CursorSet`, you no longer need an external script/process and `CursorMove` to save and restore the cursor.

2021-02-24 10:53 UTC, ThomasAdam requested changes
Hi @mikeandmore 

I suppose the idea makes sense, but I really don't want a separate command for this.  If it were going to be included in `fvwm3` then I'd want it part of `CursorMove` somehow.  The long-term goal is to reduce commands, not increase them.

You'll also need to add to the man page.

2021-02-24 10:53 UTC, ThomasAdam commented on fvwm/builtins.c
> +		h = m->virtual_scr.MyDisplayHeight;
This needs correcting, as it's been a long-standing semantic bug.  `m->virtual_scr.MyDisplayWidth` and `m->virtual_scr.MyDisplayHeight` are not per-monitor values, but an aggregate of all displays connected.  Hence, you either want to set `w`/`h` to `monitor_get_all_widths()`/`monitor_get_all_heights()` respectively outside of the loop, or use `m->si->w`/`m->si->h` for per-monitor values.

I'll clean this up separately.

2021-02-25 19:32 UTC, mikeandmore commented
let me work on adding this into `CursorMove`. In that case i'll reuse the code left there before.

2021-02-26 15:11 UTC, mikeandmore commented
This commit will reuse the `CursorMove` command.

2021-02-26 15:19 UTC, mikeandmore commented
I separate the commit this time.

2021-02-26 16:23 UTC, ThomasAdam commented
Thanks.  Now we can clean things up a bit further:

* Since commit 6cc71636cfbf839aeca2107a84026da3cea66585 was introduced by 728e21a67b8ed6a4f16556f8766ed95eff67aece, please squash 6cc71636cfbf839aeca2107a84026da3cea66585 into 728e21a67b8ed6a4f16556f8766ed95eff67aece
* We can probably reword the commits a  better.  For example, I would word cf85ff991100c9a1dcfdd2cc2cb7bde7800a0294 as:
```
GetTwoPercentArguments: remove unneeded PeekToken

Remove an unneeded call to PeekToken as this is never used.
```

2021-02-27 23:15 UTC, merged